[build]
  publish = ".next"
  command = "npm run build"


[[headers]]
for = "/*"

  [headers.values]
  X-Frame-Options = "DENY"
  Content-Security-Policy = "frame-ancestors 'none';"

[[headers]]
for = "/_astro/*"

  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"


[context.main]

    [context.main.images]
    remote_images = []

    [[context.main.headers]]
    for = "/*"

      [context.main.headers.values]
      X-Frame-Options = "DENY"
      Content-Security-Policy = "frame-ancestors 'none';"

    [[context.main.headers]]
    for = "/_astro/*"

      [context.main.headers.values]
      Cache-Control = "public, max-age=31536000, immutable"