[build]
  publish = ".next"
  command = "npm run build"


[[headers]]
  for = "/*"
  [headers.values]
  Content-Security-Policy = "script-src 'nonce-__CSP_NONCE__' 'strict-dynamic' 'self' https:; report-uri /.netlify/functions/__csp-violations"